import {
  Controller,
  Post,
  Headers,
  Req,
  HttpCode,
  HttpStatus,
  UnauthorizedException,
  Logger,
  Body,
} from '@nestjs/common';
import { ApiTags, ApiOperation, ApiResponse, ApiHeader } from '@nestjs/swagger';
import { Request } from 'express';
import { WebhookService } from './webhook.service';

@ApiTags('Webhooks')
@Controller('webhooks')
export class WebhookController {
  private readonly logger = new Logger(WebhookController.name);

  constructor(private readonly webhookService: WebhookService) {}

  @Post('github')
  @HttpCode(HttpStatus.OK)
  @ApiOperation({ summary: 'GitHub Webhook ingress endpoint' })
  @ApiHeader({ name: 'x-github-event', description: 'GitHub event type (e.g. push, ping)' })
  @ApiHeader({ name: 'x-hub-signature-256', description: 'HMAC-SHA256 signature generated by GitHub' })
  @ApiResponse({ status: 200, description: 'Webhook acknowledged and queued' })
  @ApiResponse({ status: 401, description: 'Invalid HMAC signature' })
  async handleGithubWebhook(
    @Headers('x-github-event') event: string,
    @Headers('x-hub-signature-256') signature: string | undefined,
    @Req() req: Request,
    @Body() body: any
  ) {
    const rawBody = (req as any).rawBody || JSON.stringify(body);

    // Verify signature
    const isValid = this.webhookService.verifySignature(signature, rawBody);
    if (!isValid) {
      this.logger.warn('Rejected GitHub webhook with invalid signature');
      throw new UnauthorizedException('Invalid GitHub signature.');
    }

    // Acknowledge ping events
    if (event === 'ping') {
      this.logger.log('Received GitHub ping event.');
      return { ok: true, message: 'pong' };
    }

    // Process push events
    if (event === 'push') {
      const result = await this.webhookService.handlePushEvent(body);
      return {
        ok: true,
        ...result,
      };
    }

    return {
      ok: true,
      message: `Ignored unhandled GitHub event type: ${event}`,
    };
  }
}
